version: '3.8'

networks:
  ory-network:
    driver: bridge
  book-looker-realm:
    driver: bridge

volumes:
  postgres-data:
  hydra-secrets:
  kratos-secrets:
  keto-data:

services:
  # PostgreSQL Database for Ory services
  postgres:
    image: postgres:15-alpine
    container_name: ory-postgres
    environment:
      POSTGRES_DB: ory
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory-secret
      POSTGRES_MULTIPLE_DATABASES: hydra,kratos,keto
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - ory-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ory -d ory"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ory Hydra - OAuth2 and OpenID Connect Provider
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    container_name: hydra-migrate
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/hydra?sslmode=disable
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - ./config/hydra:/etc/config/hydra:ro
    networks:
      - ory-network
    depends_on:
      postgres:
        condition: service_healthy

  hydra:
    image: oryd/hydra:v2.2.0
    container_name: ory-hydra
    ports:
      - "4444:4444" # Public endpoint
      - "4445:4445" # Admin endpoint
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - ./config/hydra:/etc/config/hydra:ro
      - ./certs:/etc/certs:ro  # Your self-signed PKI certificates
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/hydra?sslmode=disable
      SECRETS_SYSTEM: your-system-secret-32-chars-long
      URLS_SELF_ISSUER: http://localhost:4444
      URLS_CONSENT: http://localhost:3000/consent
      URLS_LOGIN: http://localhost:3000/login
      # CA trust environment variables for Go HTTP client
      SSL_CERT_FILE: /etc/certs/ca.crt
      SSL_CERT_DIR: /etc/certs
      CURL_CA_BUNDLE: /etc/certs/ca.crt
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  # Ory Kratos - Identity and User Management
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    container_name: kratos-migrate
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/kratos?sslmode=disable
    command: migrate sql -e --yes
    volumes:
      - ./config/kratos:/etc/config/kratos:ro
    networks:
      - ory-network
    depends_on:
      postgres:
        condition: service_healthy

  kratos:
    image: oryd/kratos:v1.0.0
    container_name: ory-kratos
    ports:
      - "4433:4433" # Public endpoint
      - "4434:4434" # Admin endpoint
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./config/kratos:/etc/config/kratos:ro
      - ./config/kratos/identity.schema.json:/etc/config/kratos/identity.schema.json:ro
      - ./config/kratos/hooks:/etc/config/kratos/hooks:ro
      - ./certs:/etc/certs:ro  # Mount CA certificate for SSL trust
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/kratos?sslmode=disable
      LOG_LEVEL: trace
      # CA trust environment variables for Go HTTP client
      SSL_CERT_FILE: /etc/certs/ca.crt
      SSL_CERT_DIR: /etc/certs
      CURL_CA_BUNDLE: /etc/certs/ca.crt
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  # Ory Keto - Fine-grained Authorization
  keto-migrate:
    image: oryd/keto:v0.11.1
    container_name: keto-migrate
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/keto?sslmode=disable
    command: migrate up --yes
    volumes:
      - ./config/keto:/etc/config/keto:ro
    networks:
      - ory-network
    depends_on:
      postgres:
        condition: service_healthy

  keto:
    image: oryd/keto:v0.11.1
    container_name: ory-keto
    ports:
      - "4466:4466" # Read API
      - "4467:4467" # Write API
      - "4468:4468" # OPL API
    command: serve -c /etc/config/keto/keto.yml
    volumes:
      - ./config/keto:/etc/config/keto:ro
      - ./certs:/etc/certs:ro  # Mount CA certificate for SSL trust
    environment:
      DSN: postgres://ory:ory-secret@postgres:5432/keto?sslmode=disable
      # CA trust environment variables for Go HTTP client
      SSL_CERT_FILE: /etc/certs/ca.crt
      SSL_CERT_DIR: /etc/certs
      CURL_CA_BUNDLE: /etc/certs/ca.crt
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      keto-migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  # Ory Oathkeeper - Identity & Access Proxy
  oathkeeper:
    image: oryd/oathkeeper:v0.40.6
    container_name: ory-oathkeeper
    ports:
      - "4455:4455" # Proxy port
      - "4456:4456" # API port
    command: serve -c /etc/config/oathkeeper/oathkeeper.yml
    volumes:
      - ./config/oathkeeper:/etc/config/oathkeeper:ro
      - ./certs:/etc/certs:ro  # Your self-signed PKI certificates
    environment:
      LOG_LEVEL: debug
      # CA trust environment variables for Go HTTP client
      SSL_CERT_FILE: /etc/certs/ca.crt
      SSL_CERT_DIR: /etc/certs
      CURL_CA_BUNDLE: /etc/certs/ca.crt
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      - hydra
      - kratos
      - keto
    restart: unless-stopped

  # MailSlurper for email testing (development only)
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: ory-mailslurper
    ports:
      - "4436:4436" # Web UI
      - "4437:4437" # API
      - "1025:1025" # SMTP
    networks:
      - ory-network

  # Kerby-instruments - Kerberos Principal Management
  # This service is in development - placeholder configuration
  kerby-instruments:
    # image: book-looker-realm/kerby-instruments:latest  # When available
    image: nginx:alpine  # Temporary placeholder
    container_name: kerby-instruments
    ports:
      - "8443:443"   # HTTPS endpoint
      - "8080:80"    # HTTP endpoint (development)
    environment:
      # Kerberos realm configuration
      KRB_REALM: "BOOK-LOOKER.REALM"
      KRB_KDC_HOST: "localhost"
      KRB_KDC_PORT: "88"
      
      # Database configuration (when implemented)
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "kerby_instruments"
      DB_USER: "ory"
      DB_PASSWORD: "ory-secret"
      
      # Integration tokens
      KRATOS_WEBHOOK_TOKEN: "kerby-instruments-service-token"
      HYDRA_CLIENT_ID: "kerby-instruments-client"
      
      # Certificate management
      PKI_ROOT_CA_PATH: "/app/certs/ca"
      PKI_INTERMEDIATE_CA_PATH: "/app/certs/intermediate"
      X509_CERT_VALIDITY_DAYS: "365"
    volumes:
      # Certificate storage
      - ./certs:/app/certs:rw
      # Configuration when available
      # - ./config/kerby-instruments:/app/config:ro
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # When implemented, health check will be:
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "https://localhost:8443/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  # PKI Services for Certificate Management
  pki-services:
    image: nginx:alpine
    container_name: pki-services
    ports:
      - "8080:80"    # CRL and OCSP endpoints
    environment:
      - NGINX_PORT=80
    volumes:
      - ./certs:/var/www/html/certs:ro
      - ./pki-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ory-network
      - book-looker-realm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Simple OCSP Responder (for development/testing)
  ocsp-responder:
    image: alpine:latest
    container_name: ocsp-responder
    ports:
      - "8081:8081"  # OCSP responder port
    command: |
      sh -c "
        apk add --no-cache openssl socat &&
        cd /app/certs &&
        echo 'Starting OCSP Responder on port 8081...' &&
        while true; do
          echo 'OCSP Responder ready' | socat TCP-LISTEN:8081,fork,reuseaddr SYSTEM:'openssl ocsp -port 8081 -text -CA ca.crt -index ca/index.txt -rkey ocsp/ocsp.key -rsigner ocsp/ocsp.crt -nrequest 1'
        done
      "
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - ory-network
      - book-looker-realm
    depends_on:
      - pki-services
    restart: unless-stopped

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ory-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - ory-network
