version: v2.2.0

# Hydra Configuration for book-looker-realm
serve:
  public:
    port: 4444
    host: 0.0.0.0
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      allowed_headers:
        - "*"
      exposed_headers:
        - "*"
  admin:
    port: 4445
    host: 0.0.0.0

dsn: postgres://ory:ory-secret@postgres:5432/hydra?sslmode=disable

urls:
  self:
    issuer: http://localhost:4444
  consent: http://localhost:3000/consent
  login: http://localhost:3000/login
  logout: http://localhost:3000/logout
  error: http://localhost:3000/error
  post_logout_redirect: http://localhost:3000/

secrets:
  system:
    - your-system-secret-32-chars-long

oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise
    pairwise:
      salt: your-salt-16-chars

oauth2:
  expose_internal_errors: true
  # Support for client certificate authentication (mTLS)
  client_credentials:
    default_grant_allowed_scope: false
  # PKCE support for Authorization Code Flow
  pkce:
    enforced: false
    enforced_for_public_clients: true

# Support for client certificate authentication with your self-signed PKI
strategies:
  access_token: jwt

log:
  level: debug
  format: json
